export {default as Loader} from './components/Loader'
export {default as Footer} from './components/Footer'
export {default as Welcome} from './components/Welcome'
export {default as Services} from './components/Services'
export {default as Transactions} from './components/Transactions'
export {default as Navbar} from './components/Transactions'